# Generated by Django 4.1.7 on 2023-09-21 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 21, 20, 4, 1, 124072)),
        ),
    ]
