# Generated by Django 4.1.7 on 2023-10-03 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_alter_salary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 19, 36, 24, 774984)),
        ),
    ]
