# Generated by Django 4.1.7 on 2023-10-11 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_alter_salary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
