# Generated by Django 4.2.4 on 2023-08-28 14:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50, verbose_name='Клиент')),
                ('repairer', models.CharField(max_length=50, verbose_name='Исполнитель')),
                ('whats_broken', models.CharField(max_length=50, verbose_name='Неисправность')),
                ('device_appearance', models.CharField(blank=True, default='', max_length=80, verbose_name='Состояние')),
                ('device_type', models.CharField(blank=True, default='', max_length=20, verbose_name='Тип устройства')),
                ('imei', models.CharField(blank=True, default='', max_length=20, verbose_name='IMEI/SN')),
                ('device_brand', models.CharField(max_length=20, verbose_name='Производитель')),
                ('device_model', models.CharField(max_length=20, verbose_name='Модель')),
                ('device_kit', models.CharField(blank=True, default='', max_length=80, verbose_name='Комплектация')),
                ('device_pass', models.CharField(blank=True, default='', max_length=20, verbose_name='Пароль')),
                ('price', models.IntegerField(verbose_name='Орентировоная стоимость')),
                ('note_hidden', models.CharField(blank=True, default='', max_length=150, verbose_name='Заметки клиент НЕ видит')),
                ('note_client', models.CharField(blank=True, default='', max_length=150, verbose_name='Заметки клиент видит')),
                ('prepayment', models.IntegerField(blank=True, default=0, null=True, verbose_name='Предоплата')),
                ('profit', models.IntegerField(default=0, null=True, verbose_name='Профит')),
                ('debt', models.IntegerField(default=0, null=True, verbose_name='Клиент должен')),
                ('date_creation', models.DateTimeField(default=datetime.datetime(2023, 8, 28, 14, 47, 47, 528106), null=True, verbose_name='Дата создания')),
                ('date_completion', models.DateTimeField(null=True, verbose_name='Дата готовности')),
                ('in_work', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repairer', models.CharField(max_length=50, verbose_name='Исполнитель')),
                ('payment', models.IntegerField(blank=True, default=0, verbose_name='Платёж')),
                ('work', models.CharField(max_length=50, verbose_name='Название услуги')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('cost', models.IntegerField(blank=True, default=0, verbose_name='Себестоимость')),
                ('guarantee', models.IntegerField(default=60, verbose_name='Гарантия')),
                ('discount', models.IntegerField(blank=True, default=0, verbose_name='Скидка')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('paid_by_client', models.BooleanField(default=False, verbose_name='Оплачено клиентом')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repairer', models.CharField(max_length=50, verbose_name='Исполнитель')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 8, 28, 14, 47, 47, 528801))),
                ('message', models.CharField(max_length=200, verbose_name='Сообщение')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ')),
            ],
        ),
    ]
