# Generated by Django 4.2.4 on 2023-08-30 16:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_date_creation_alter_orderhistory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 16, 17, 2, 324511), null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 16, 17, 2, 325173)),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reason', models.CharField(choices=[('PREPAYMENT', 'Предоплата'), ('ORDER_PAYMENT', 'Оплата заказа'), ('REFUND', 'Возврат предоплаты'), ('SALARY_PAYOUT', 'Выплата заработной платы')], max_length=30, verbose_name='Тип платежа')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 8, 30, 16, 17, 2, 325445), verbose_name='Дата платежа')),
                ('income', models.IntegerField(default=0, null=True, verbose_name='Приход')),
                ('expense', models.IntegerField(default=0, null=True, verbose_name='Расход')),
                ('comment', models.CharField(blank=True, default='', max_length=30, verbose_name='Комментарий')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ')),
            ],
        ),
    ]
