# Generated by Django 4.2.4 on 2023-08-30 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_date_creation_alter_orderhistory_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 17, 26, 50, 200632), null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 17, 26, 50, 201373)),
        ),
        migrations.AlterField(
            model_name='payments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 17, 26, 50, 201651), verbose_name='Дата платежа'),
        ),
    ]
