# Generated by Django 4.1.7 on 2023-09-18 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_repairer_remove_orderhistory_repairer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 18, 18, 30, 38, 594681), null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 18, 18, 30, 38, 595679)),
        ),
        migrations.AlterField(
            model_name='payments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 18, 18, 30, 38, 596676), verbose_name='Дата платежа'),
        ),
    ]
