# Generated by Django 4.1.7 on 2023-09-18 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_date_creation_alter_orderhistory_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 18, 19, 26, 14, 857041), null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 18, 19, 26, 14, 858038)),
        ),
        migrations.AlterField(
            model_name='payments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 18, 19, 26, 14, 859035), verbose_name='Дата платежа'),
        ),
    ]
