# Generated by Django 4.1.7 on 2023-09-21 16:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_date_creation_alter_orderhistory_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 21, 20, 4, 1, 122078), null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 21, 20, 4, 1, 123075)),
        ),
        migrations.AlterField(
            model_name='payments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 21, 20, 4, 1, 123075), verbose_name='Дата платежа'),
        ),
        migrations.AlterField(
            model_name='works',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payments', verbose_name='Платёж №'),
        ),
    ]
