# Generated by Django 4.1.7 on 2023-10-03 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_date_creation_alter_orderhistory_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ['-pk'], 'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterField(
            model_name='order',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 11, 3, 41, 999029), null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='prepayment',
            field=models.IntegerField(blank=True, null=True, verbose_name='Предоплата'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 11, 3, 41, 999974)),
        ),
        migrations.AlterField(
            model_name='payments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 11, 3, 41, 999029), verbose_name='Дата платежа'),
        ),
    ]
