# Generated by Django 4.1.7 on 2023-10-03 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_payments_options_alter_order_date_creation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='date',
        ),
        migrations.AddField(
            model_name='payments',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 19, 36, 24, 772989), verbose_name='Дата платежа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 19, 36, 24, 772989), null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 19, 36, 24, 773986)),
        ),
    ]
